package main

type Mention string
type Group string
type Option string
type OptionGroup string

// CODE FROM ametice.univ-amu.fr/pluginfile.php/9746522/mod_resource/content/6/%402025-08-29_-_M1_%3D_Liste_des_ECUE.pdf

const CODE_POC string = "SINA09D"
const CODE_SDD_AA string = "SINA10B"
const CODE_COMPLEXITE string = "SINA09B"
const CODE_BDD_AVANCE string = "SINA20B"
const CODE_PROBA_POUR_INFORMATIQUE string = "SINA12A"
const CODE_GENIE_LOG string = "SINA09E"
const CODE_CRYPTOGRAPHIE string = "SINA09F"
const CODE_PROG_CPP string = "SINA12B"
const CODE_DONNEES_POST_RELATIONNELLES string = "SINA20B"
const CODE_PROG_FONCTIONNELLE string = "SINA12A"
const CODE_RESEAUX string = "SINA09A"
const CODE_METHODE_NUM_INFORMATIQUE string = "SINA13A"
const CODE_SECURITE_DES_APPS string = "SINA10A"
const CODE_GESTION_PROJETS string = "SINA11B"

const CODE_ANALYSE_DES_DONNEES string = "SINB44B"
const CODE_ARCHITECTURES_JEE string = "SINB44D"
const CODE_ANGLAIS_DE_INFORMATIQUE string = "SINB35B"
const CODE_ALGORITHMES_A_PERFORMANCES_GARANTIES string = "SINB33B"
const CODE_ANALYSE_DE_PROGRAMMES string = "SINB33G"
const CODE_ALGORITHMIQUE_ET_RECHERCHE_OPERATIONNELLE string = "SINB33E"
const CODE_ALGORITHMES_ET_SYSTEMES_ROBUSTES string = "SINB33H"
const CODE_BASES_DE_APPRENTISSAGE_ARTIFICIEL string = "SINB37A"
const CODE_CALCULABILITE_AVANCEE string = "SINB40A"
const CODE_DES_CONTENEURS_AU_CLOUD string = "SINB34B"
const CODE_COMMUNICATION_SCIENTIFIQUE_ET_PROFESSIONNELLE string = "SINB33F"
const CODE_EXPLORATION_DES_DONNEES string = "SINB49A"
const CODE_FIABILITE_LOGICIELLE string = "SINB34A"
const CODE_GENIE_LOGICIEL_AVANCE string = "SINB33D"
const CODE_INTEGRATION_DES_DONNEES string = "SINB44A"
const CODE_INTERFACE_HUMAIN_MACHINE string = "SINB38B"
const CODE_INFORMATIQUE_QUANTIQUE string = "SINB33A"
const CODE_MODELISATION_GEOMETRIQUE_ET_MAILLAGES string = "SINB37D"
const CODE_MODELISATION_ET_RESOLUTION_POUR_LA_DECISION string = "SINB41A"
const CODE_PROGRAMMATION_GRAPHIQUE string = "SINB38A"
const CODE_RESEAUX_DE_NEURONES string = "SINB46A"
const CODE_SURFACES_DE_FORME_LIBRE string = "SINB37C"
const CODE_TRAITEMENT_AUTOMATIQUE_DES_LANGUES string = "SINB44C"
const CODE_THEORIE_DE_LA_COMPLEXITE string = "SINB33C"
const CODE_TRAVAUX_ETUDE_ET_RECHERCHE string = "SINB35A"
const CODE_THEORIE_STRUCTURELLE_DES_GRAPHES string = "SINB37B"